api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "free-gift-discount"
type = "function"
uid = "23c96fdf-71ac-f39b-5536-97145ee1e800d1e209ee"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
